### ISSUE TITLE
Update payment fee after company is changed

### ISSUE THREAD

**Issue by dhacquebord** [Billinkbv/module-billink-hyva#5]
First off: Thanks for adding the payment fee! 💪🏼 

I'm trying to integrate this at this moment but noticed a little bug: The payment fee only gets updated when changing the payment method.

Steps to reproduce:
1. Configure a payment fee for B2B customers
2. Keep the company field in your address empty
3. Select Billink as a payment method
4. Check: No payment fee should be added to the order totals.
5. Add a company name
6. Check: Still no payment fee in order totals, i would expect them to appear at this point
7. Switch to another payment method (doesn't matter which one)
8. Switch back to Billink
9. Check: Payment fees will be added

So what do i expect:
- Billink fee will be updated when changing company
- Billink fee will be updated when switching from an existing address without a company name to an existing address with a company name

**Comment by dhacquebord** [comment]
I just noticed that @DarthFly has opened a PR containing a fix for this issue. Just referencing it here for other readers: https://github.com/Billinkbv/module-billink-hyva/pull/7

**Comment by Billinkbv** [comment]
Hi @dhacquebord, this should be fixed in the last release.
